# Generated by Django 4.2.2 on 2023-06-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_images/user.png', null=True, upload_to='profile_images/'),
        ),
    ]
