# Generated by Django 4.2.2 on 2023-06-19 14:34

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(
                blank=True, default='default_images/user.png', null=True, upload_to='profile_images/'),
        ),
    ]
